### ISSUE TITLE
Send Alerts to Users

### ISSUE THREAD

**Issue by crimsonangel68** [TheLoons/SportIM-service#26]

**Comment by hjbrock** [comment]
http://quartz-scheduler.org/documentation/quartz-2.x/quick-start

**Comment by hjbrock** [comment]
arch.maven.org/#search%7Cga%7C1%7Cg%3A%22org.quartz-scheduler%22

**Comment by hjbrock** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.quartz-scheduler%22

**Comment by crimsonangel68** [comment]
1. Make sure job isn't running (AlertJob table (Column "isRunning" (true/false?))) (bail out if running)
2. Grab Events from now to 24 hours + participants + preferences (from teams/participants) (AKA Nasty Join)
3. Make sure not already fired (via Alerts Table (Columns: eventId, login, start))
4. For each login/event pair fire alert and add to alerts
5. Clear out old alerts
6. Change job to "not running"

**Comment by hjbrock** [comment]
https://devcenter.heroku.com/articles/sendgrid

**Comment by hjbrock** [comment]
http://stackoverflow.com/questions/19573457/simple-example-for-quartz-2-2-and-tomcat-7
