### ISSUE TITLE
Not able to PUT with leagues, always returns 'Invalid Team Id'

### ISSUE THREAD

**Issue by boccobrock** [TheLoons/SportIM-service#44]
Using League id 21, I am unable to save changes to the league.

**Comment by hjbrock** [comment]
Could you put the JSON you're trying to PUT here?

**Comment by hjbrock** [comment]
Actually, I probably know what's happening looking at code. You're putting to:

/rest/league/{id}

Right? Looks like that was co-opted for adding a team to a league so you can't use it for generic league changes. Put to:

/rest/league

And just make sure the league ID is in the JSON. We can change this, but Doug should do it as it's a rewrite of his code.

**Comment by hjbrock** [comment]
Alright, you can use the old URLs for typical team/league PUTs again:

/rest/league/{leagueID}
/rest/team/{teamID}

I've moved the player-to-team addition to:

/rest/team/{teamID}/add?login=

And the team-to-league addition to:

/rest/league/{leagueID}/add?teamId=
