### ISSUE TITLE
Backend not returning teams

### ISSUE THREAD

**Issue by boccobrock** [TheLoons/SportIM-service#45]
Logged in as rimando@test.com, getting teams from /team returns no teams, despite the user being an owner of 3 teams.

**Comment by hjbrock** [comment]
Are you using rest/team/edit or rest/team/view?

**Comment by hjbrock** [comment]
I just tested this. The bare /team GET was put in to get teams from a league. If you don't have the league parameter, you won't get anything back.

As long as you're using the endpoint I actually specified in my tickets for this, it works:

/rest/team/view - teams the user can view and require in events
/rest/team/edit - teams the user can edit
